### ISSUE TITLE
Carousel viewer does not load when item has only pdf or html media

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/centerrow#11]
Based on a [post on the forum](https://forum.omeka.org/t/collecting-module-issue-w-displaying-item-media-html-prompt-data/2499) I tested this with attached HTML media and a PDF media upload. On the public item show page, the carousel sticks on a spinning 'loading' icon. It's possible to stop the loading but there is not a readily apparent way to open that media (as a new page, the way it works on default and cozy). Also true in TheDaily.

![screen shot 2016-12-14 at 11 10 45 am](https://cloud.githubusercontent.com/assets/2314070/21190023/77780428-c1ee-11e6-9cee-a89b1edf11fe.png)

**Comment by jairomelo** [comment]
Center Row is a nice theme, but lack of visualization of PDF files in carousel is a serious issue. I wonder if  @jimsafley has any possible solutions for this issue, could be a problem with ImageMagick? I don't know, anyone else have the same problem?

**Comment by kimisgold** [comment]
Non-image media is now sorted into a list of links lower on the page, and there is some video support thanks to a new suite of plugins. 

@jairomelo I'm somewhat at the mercy of the file types the carousel and lightbox plugins support, and none of the ones I've found that are also presently maintained offer PDFs as a displayable file type. PDFs should now appear as "Other Media" lower on the page, and link to a version of the PDF that is rendered by the browser.
