### ISSUE TITLE
Contibution block is printing all forms

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-themes/centerrow#12]
If the user has a choice of contribution forms, the drop down menu is public, but also the forms themselves are printing on the page.
<img width="1025" alt="firefoxscreensnapz004" src="https://cloud.githubusercontent.com/assets/741480/26063689/b90caaf2-395c-11e7-985f-ccc10019fcbb.png">

**Comment by sharonmleon** [comment]
Looks like this is a javascript error. It's killing the simple search link, too.

GET 
http://chnmdev.gmu.edu/RI/application/asset/vendor/jquery/jquery.min.js [HTTP/1.1 404 Not Found 314ms]
GET 
http://chnmdev.gmu.edu/RI/application/asset/vendor/jquery/jquery.min.js [HTTP/1.1 404 Not Found 281ms]
GET 
http://chnmdev.gmu.edu/RI/application/asset/vendor/jquery/jquery.min.js [HTTP/1.1 404 Not Found 259ms]
GET 
http://chnmdev.gmu.edu/RI/application/asset/vendor/jquery/jquery.min.js [HTTP/1.1 404 Not Found 351ms]
GET 
http://chnmdev.gmu.edu/RI/application/asset/vendor/jquery/jquery.min.js [HTTP/1.1 404 Not Found 284ms]
ReferenceError: jQuery is not defined[Learn More]  centerrow.js:10:1
Error: jQuery should be loaded before CKEditor jQuery adapter.  jquery.js:5:45
ReferenceError: $ is not defined[Learn More]  collecting-block.js:1:1

**Comment by zerocrates** [comment]
I think this may be a case of having an updated centerrow but a not-updated-enough core.

Try updating to the latest S and see if that helps.

**Comment by sharonmleon** [comment]
Fixed!
