### ISSUE TITLE
Selecting asset for logo a bit confusing

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-themes/centerrow#14]
When I go to the theme settings and want to add an asset for the logo, I get this in the sidebar

![selectlogo](https://cloud.githubusercontent.com/assets/153262/26512869/93ce8188-4236-11e7-957d-eadb859702b9.png)

But, clicking "Upload" pops up a message telling me to select a file, seemingly pointing me to the "Browse" button, which is what gets me to the modal for uploading a file. So, it's a little odd to have a heading that says "Upload new asset", then an "Upload" button that doesn't seem to do anything. 

This is in FF, Linux Mint.

**Comment by patrickmj** [comment]
Ah...now I see that it's 1) Browse to select the file, 2) click upload to put it in the list below in the sidebar. Then, presumably, save the changes. Surprised me that the upload happened before saving the page.

**Comment by zerocrates** [comment]
Upload actually uploads, once you've browsed for a file.

This is core UI so should be filed there.

**Comment by patrickmj** [comment]
Moved to https://github.com/omeka/omeka-s/issues/936
