### ISSUE TITLE
Doesn't know what to do with HTML media

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-themes/centerrow#17]
Going to a site/item page, where the item only has HTML media, produces a big black space, but no HTML media. Looks like there's a link to view the media, but I would have liked some kind of switch to handle the HTML media on the item page.

**Comment by kimisgold** [comment]
Can you provide an example of the HTML media you're trying to use?

**Comment by patrickmj** [comment]
Huh. Now I'm not able to reproduce it, so not sure what's up.

The HTML was just

```
<p><strong>HTML</strong></p>

<p>and para text</p>
```

**Comment by patrickmj** [comment]
I take that back, after getting to the correct url: like `/omekas/s/site1/item/1`

HTML is just

```
<p><strong>HTML</strong></p>

<p>and para text</p>
```

**Comment by kimisgold** [comment]
The lightbox is only intended to display media that its plugins support, namely images and certain streaming video (youtube and vimeo). Anything that doesn't fit the bill gets a link in the "Other Media" section. The above commit (9a2009c1a3988b639414e4e40c32858753ca4ab6) should at least prevent that big empty box from appearing.

**Comment by patrickmj** [comment]
So, the big empty box is gone. It seems, though, like HTML media wouldn't require a click-through to see it, since it's just HTML for the item. Not sure how big a thing this is for the RC, but I wouldn't be surprised by people expecting different behavior.

**Comment by kimisgold** [comment]
@patrickmj This is a theme specifically oriented towards displaying visual media. Your example HTML media attachment (a sample of HTML text) feels like an outlier for use in this theme as well as difficult to integrate into the lightbox plugin. If you provide another more likely and overlooked use case, I'll see what I can do.

**Comment by patrickmj** [comment]
Yeah, I see that. We'll get questions, but I'm good dealing with that.
