### ISSUE TITLE
Long subnavigation bumps content down when first block is item showcase

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-themes/centerrow#18]
Haven't explored yet whether a similar thing happens in other contexts, but when I have a first block that's item showcase, and a long list of subnavigation pages, the navigation bumps the images for the showcase down, creating a big white space.

![centerrownav](https://user-images.githubusercontent.com/153262/30704678-673dd8e8-9ec1-11e7-986e-86ddf6877b0e.png)

**Comment by patrickmj** [comment]
To clarify, the first block _besides_ the title block. Same with other block types

**Comment by kimisgold** [comment]
@patrickmj Can you pull and confirm https://github.com/omeka-s-themes/centerrow/commit/331ae4962835b48aac8fadd220620f7178941b31 fixes this issue? This uses a flexbox solution, so you might also want to check other pages that either don't feature the subnavigation or include special module content.

**Comment by patrickmj** [comment]
No dice. The title moved a bit, but the whitespace remains. I'm not sure if this is new or not, but I also noticed that my item with metadata block below the showcase block doesn't work with the prev-next navigation.

![centerrownewtop](https://user-images.githubusercontent.com/153262/30712160-10ed0942-9ed9-11e7-8e45-c75f25187834.png)


![centerrownewfoot](https://user-images.githubusercontent.com/153262/30712164-1998c0b8-9ed9-11e7-912b-c38617ae9492.png)

**Comment by kimisgold** [comment]
Sorry, I forgot to mention you should pull from core, as there's now a wrapper that helps lay out the site blocks. (https://github.com/omeka/omeka-s/commit/7307beed207ccdae02addc614b8b6f882b77fd88)

**Comment by patrickmj** [comment]
Ah! Indeed, that looks like it fixes it to me. Haven't bopped around different page and block types, nor modules adding stuff yet. but the immediate issue seems solved.
