### ISSUE TITLE
Title label and title overlap

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-themes/centerrow#19]
Looks like the recent style changes leave the Title label and the actual title fighting it out for their space in an item with metadata block. Title of the item is "HTML Media"

![crtitle](https://user-images.githubusercontent.com/153262/30715150-4e850f5c-9ee3-11e7-8996-ec14a372b95f.png)

**Comment by kimisgold** [comment]
I'm having trouble reproducing this. 

This is my public view:
![screen shot 2017-09-21 at 5 27 07 pm](https://user-images.githubusercontent.com/606764/30719645-44a0cbf2-9ef2-11e7-975d-fd04eb3923f9.png)

This is my page edit view:
![screen shot 2017-09-21 at 5 27 32 pm](https://user-images.githubusercontent.com/606764/30719662-52179cfc-9ef2-11e7-97d1-11cb350393db.png)
