### ISSUE TITLE
Email and get embed code font not rendering correctly.

### ISSUE THREAD

**Issue by hydrosIII** [omeka-s-themes/centerrow#22]
Hi, the buttons in the bottom, to share by email and get embedded font, have an issue rendering the font. I have tested on firefox and chromium browsers. 
![captura de pantalla -2018-08-07 23-59-50](https://user-images.githubusercontent.com/7807363/43817265-269aceca-9a9e-11e8-9d9a-aaa0244b4dc8.png)

**Comment by hydrosIII** [comment]
It stills exists in recent versions of the theme

**Comment by kimisgold** [comment]
This should now be fixed, as of v1.6.0 of the theme and Sharing v1.2.0.
