### ISSUE TITLE
Strange formatting for Other Media

### ISSUE THREAD

**Issue by alexroseb** [omeka-s-themes/centerrow#23]
I’m using the centerrow theme as a base for my theme development, but I’m running into an issue that I can’t seem to figure out. When multiple Other Media or Item Sets are present, it puts this horizontal line after the first and smushes the other two together in a right-aligned section under the line. Example below, where Syllabus, Course Schedule, and Rules and Accommodations are three media attached to this item.
![Other Media](https://user-images.githubusercontent.com/8887194/48674804-50af1d80-eb1e-11e8-9785-25439944738a.png)

I’ve tried adding breaks after each in `item/show.phtml`, but it only affected the first item and everything else stayed the same.

**Comment by zerocrates** [comment]
What happened with the response you got to this same question on the forums?

**Comment by alexroseb** [comment]
@zerocrates sorry, was finally able to test it out, and it worked!

> This looks like a bug in the theme… the simplest solution is probably to put a `<div class="values"> </div>` around the foreach loops for Item Sets and Other Media in item/show.phtml.

**Comment by zerocrates** [comment]
Okay, good to hear.

We've fixed the bug already here so the next release of the theme shouldn't have this problem.
