### ISSUE TITLE
Sharing breaks layouts if at top of page

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/centerrow#24]
Discovered via [this forum post](https://forum.omeka.org/t/theme-center-row-mapping/8402/2)

If the sharing buttons are at the top of the page, they break the alignment of the labels and cause mapping blocks to conform to the width of the other content on the page, rather than full page width. Example [on my dev site](http://dev.omeka.org/mebrett/testomekas/s/austen/page/justmap)

**Comment by kimisgold** [comment]
Fixed in https://github.com/omeka-s-themes/centerrow/commit/a97a3f99778a2af6d6ffe8bd055c85da1f9007b2.
