### ISSUE TITLE
Test new layout configuration.

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/centerrow#26]
Center Row now has a configuration setting that offers options for item browse views. The browse view can now display as a single column list, the original grid layout, or provide a toggle for both.

**Comment by mebrett** [comment]
Behavior is as expected however I found a bug

**Comment by emmareisz** [comment]
This works great for standard item browse - thanks! 
But there are a few situations where Browse seems to use "list" regardless of the option selected.
- "Browse Preview" block ("Items" or any other type)
- "Browse Item Sets"
Before the update, these displayed as a grid, but they now always appear as a list.

**Comment by kimisgold** [comment]
Hi @emmareisz, it's great that you like the new setting! It's now been extended to cover item sets and the the browse preview block. We still need to test these changes before including them in a formal release, but in the meantime, you're welcome to pull the latest changes to see them in action. Thanks for bringing the issue to our attention.

**Comment by emmareisz** [comment]
Thanks so much @kimisgold - pulled the commit, and it looks fab on [our project](http://reframingimperialwar.net). Thanks again!
