### ISSUE TITLE
Item sets display oddly on Item with Metadata block

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/centerrow#29]
This is true for both Center Row and Cozy. 
If there is more than one item set, the second item set shows up right-aligned rather than next to or below the first item set.

![Screen Shot 2019-12-09 at 10 55 04 AM](https://user-images.githubusercontent.com/2314070/70451465-6b2e9e80-1a73-11ea-8ff4-418bb92c91c9.png)

**Comment by kimisgold** [comment]
The main branch of Center Row should have a fix that translates the customisations for item show to the item w/ metadata block, including support for the image viewer and non-image file links.

**Comment by kimisgold** [comment]
[Cozy should now have a similar fix.](https://github.com/omeka-s-themes/cozy/commit/86eb3360f0aae8c7082c6f07234b3e8196d4ae16)

**Comment by mebrett** [comment]
It's fixed for me in Cozy but I'm still seeing it in CenterRow

**Comment by kimisgold** [comment]
It would've been useful for me to include the new markup. Should be fixed now.

**Comment by mebrett** [comment]
And now it looks elegant
