### ISSUE TITLE
Test new core page block styles

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/centerrow#30]
See omeka/omeka-s#1480. Center Row currently solely uses the core's styles for pages, and we're looking for Center row to not look radically different with this reorganization of styles.

Test with Omeka S on `block-styles` branch and Center Row's master branch.

**Comment by mebrett** [comment]
Media Embed block accent bars extend into the text of the nearby (placed above in block order) html block
<img width="389" alt="Screen Shot 2020-01-06 at 4 20 10 PM" src="https://user-images.githubusercontent.com/2314070/71849663-93c0ad00-30a0-11ea-99de-abaf46c86776.png">

**Comment by kimisgold** [comment]
Should be fixed in https://github.com/omeka/omeka-s/commit/34e4b1c1b2c8c32333c65295493e508a31f5f609 on the core's `block-styles` branch. Try pulling—it should take care of https://github.com/omeka-s-themes/papers/issues/1 as well.

**Comment by mebrett** [comment]
That fixed it! Everything looks good.
