### ISSUE TITLE
Thumbnail sizing wrong on browse preview block

### ISSUE THREAD

**Issue by zerocrates** [omeka-s-themes/centerrow#36]
There's some issues with positioning/sizing of thumbnails in the browse preview block. The same ones work fine on the real browse page. I assume the issue is probably something simple like styles being applied only in one place but not the other.

**Comment by kimisgold** [comment]
I've pushed a fix for this issue that's ready to be tested. On the `master` branch, test that the thumbnails used in the browse preview site block matches the thumbnail sizes and styling on regular item browse views.

**Comment by sharonmleon** [comment]
@kimisgold My thumbnail sizes seem to be all fine here, but I've discovered that if I have nested pages, the top page in my navigation is not clickable on Firefox on my Ipad. I think I successfully cleared my cache. Works fine in Safari.

Maybe this is an existing glitch, but maybe it's about other recent changes.

**Comment by kimisgold** [comment]
My understanding is that Firefox and Safari are both built on webkit for iOS, so they should render the same. I'll look into this.

I'm pretty sure that's a separate issue though. Would you say the browse preview block is looking good enough to consider his resolved?

**Comment by sharonmleon** [comment]
I believe so, but I haven't tested it on a PC. I'll do that, and then close.

**Comment by sharonmleon** [comment]
All clear on the PC in Firefox, Chrome, and Edge.
