### ISSUE TITLE
Metadata Browse reads poorly in Item With Metadata block

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/centerrow#4]
On the individual item pages, the phrase "See all items with this value" displays beneath the value, clearly separating it from the actual value of the property.

However, on Item With Metadata blocks, it is displayed right next to the property value. If that value is a linked item, there's no clear visual marker between the linked item title and the button, except for a slight misalignment of the text. 

![screen shot 2016-10-21 at 3 29 06 pm](https://cloud.githubusercontent.com/assets/2314070/19609710/b4ffb772-97a6-11e6-80a0-2f676c509e34.png)

If possible, it would be nice to have a clearer visual distinction between linked item title and metadata browse button

**Comment by sheilabrennan** [comment]
I agree, but wonder if this can be made an enhancement for a future revision?

**Comment by kimisgold** [comment]
Okay, item with metadata as well as item/show should have some improvements now.
