### ISSUE TITLE
Test new flyout navigation feature

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/centerrow#46]
I've created a branch, `superfish-menu`, for a new dropdown/flyout navigation feature, as requested in #25. 

This branch supports 2 child levels of navigation within the top bar.
* On desktop resolutions, the first level will unfurl down, then the second level will open right. If the second level would run off the screen, it will move left of the first level.
* On mobile resolutions, the user may now toggle the main navigation open and closed. When the navigation is open, it is single column and expands downwards.

This needs to be tested on both desktop and mobile browsers.

**Comment by katknow** [comment]
@kimisgold I can only get it to look like this in browsers and on mobile:
<img width="1382" alt="Screen Shot 2021-07-27 at 10 39 55 PM" src="https://user-images.githubusercontent.com/84726696/127255291-18f39808-a63c-4c3c-9e56-25e5c9e3e041.png">

If you click the nav bar, it just takes you to that page no dropdown of any kind. Cleared cache/hard refreshed etc., still nothing. Double checked and I am on the superfish-menu branch, but if I pull I get a message saying there is no tracking information for that branch so I don't know if that might have anything to do with it.

**Comment by sharonmleon** [comment]
http://6floors.org/workspace/omeka-s/s/bigdata/page/welcome

I get all of my menus where they are supposed to be, but none of the links are clickable except for on the Android phone.

Desktop MacOS Firefox, Safari, Chrome. 
Android phone. IPad.

**Comment by katknow** [comment]
I have no idea why, but it looks different (and works) on Firefox on my Mac:
<img width="1429" alt="Screen Shot 2021-07-28 at 4 09 47 PM(1)" src="https://user-images.githubusercontent.com/84726696/127390097-90265e56-5574-47a9-8413-f0f18f7a53b7.png">


However, everywhere else on laptops (including Firefox on PC) it looks like this and isn't clickable (it seems to be the same as Sharon's?):
![image](https://user-images.githubusercontent.com/84726696/127389019-df2355a7-7c9a-44f5-82e5-2117a3c54732.png)

Everything seems to work nicely across mobile browsers.

**Comment by katknow** [comment]
Just checked, and both versions of Firefox are up-to-date. It worked on Firefox on macOS Big Sur and not on Firefox for Windows 10.

**Comment by sharonmleon** [comment]
Are those links function in Firefox for Mac?

**Comment by katknow** [comment]
Yes, they are functional.

**Comment by kimisgold** [comment]
@katknow Can you double check and hard refresh on Firefox for macOS?

**Comment by katknow** [comment]
Okay, switched to master and back then hard refresh and now it's the same as the others.

**Comment by sharonmleon** [comment]
The only thing I have in my console is the following warning:

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

**Comment by kimisgold** [comment]
I've just pushed a fix for the unclickable links. It's ready to pull and test again @sharonmleon and @katknow.

**Comment by sharonmleon** [comment]
Victory! Fully functioning as intended across MacOS browser, iPad, and Android phone.

**Comment by katknow** [comment]
Works across browsers on laptop and mobile for me as well! Only thing is now on mobile homepage the sidebar is a little close to the text:

![image](https://user-images.githubusercontent.com/84726696/127511155-1d9acde3-9214-41c6-a1d4-d28122b1b693.png)

Don't know if that's just because the structuring of my pages, though.

**Comment by kimisgold** [comment]
@katknow That sidebar looks different because its changes are on a different branch. We don't have to worry about it for this issue, but thanks for looking out.

**Comment by kimisgold** [comment]
This is still having issues on touch devices, and I haven't had successful communication with the plugin developers on how to fix it. I think at this point I'm going to look for an alternative solution to implement.

**Comment by kimisgold** [comment]
I have an alternative approach to these menus that are friendlier to touch devices. It uses the Adobe Accessible Megamenu, which we currently use in the Thanks, Roy themes. This approach differs from the superfish branch in a few ways: 

* Parent navigation items only open their subnavigation, which includes a direct link to the parent link. This is to reduce behavior confusion for what the top level item should do (i.e. should it open subnav or go to a url?)
* Subnavigation now appears in a full-width menu. Subsequent subnavigation appears as indented lists. This plugin didn't have easy methods of detecting whether flyout menus should appear left or right based off space allotted, and this will better accommodate large navigation items and trees.

This should be tested on desktop and mobile browsers using the `adobe-accessible-menu` branch.

**Comment by sharonmleon** [comment]
@katknow Want to give this a spin?

**Comment by katknow** [comment]
@sharonmleon can do!

**Comment by katknow** [comment]
@kimisgold it may be user error, but when I try to checkout the branch I get:

error: pathspec 'adobe-accessible-menu' did not match any file(s) known to git

**Comment by kimisgold** [comment]
Hmm, it definitely exists here: https://github.com/omeka-s-themes/centerrow/tree/adobe-accessible-menu. Can you try pulling again before checking out?

**Comment by katknow** [comment]
It took a few pulls throughout the day, but for some reason it did eventually let me switch branches! Seems to work well across browsers and mobile devices. The full width nav-bar is interesting--I've not seen many sites with horizontally oriented sub-navigation (desktop and tablets). The navigation remains vertically oriented on mobile, but also shows the full width.

**Comment by kimisgold** [comment]
The full width megamenu approach is one we do in the default Omeka S theme, and I thought I'd replicate it here based off the complex navigation I've seen in our users' sites. (Not to mention it was easier than coming up with a custom solution to determine submenu positioning with this particular plugin.) This all sounds according to intended use and ready to merge.
