### ISSUE TITLE
Test revised subnavigation on pages

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/centerrow#47]
Previously, the subnavigation for a page containing child pages scaled poorly for mobile devices. On the `master` branch, I've revised the subnavigation to do the following:

* On desktop resolutions, it's a little wider and uses sticky positioning to follow the content's scroll.
* On mobile resolutions, subnavigation and content condense to a single column layout, with the subnavigation sitting above the content.

These need to be tested on desktop and mobile browsers.

**Comment by kimisgold** [comment]
That looks right!

**Comment by kimisgold** [comment]
Having issues with clicking through top level navigation items on touch devices, as per @sharonmleon's comment in #36.

**Comment by katknow** [comment]
@kimisgold took another look and it seems to be working fine for me, including on Firefox for touch devices

**Comment by kimisgold** [comment]
Whoops, I had reopened the wrong issue.
