### ISSUE TITLE
Translate "Other Media"

### ISSUE THREAD

**Issue by giocomai** [omeka-s-themes/centerrow#48]
On the item page, the text "Other Media" is not translated if the language is set to something other than English. 

I see that the theme correctly asks for translation in `/view/common/block-layout/item-with-metadata.phtml`, but, as the string is apparently not present in core Omeka S, then it's not translated.

Not sure if missing translation should be reported here, on Transifex, on core, etc. - if here's not the right place, I'll welcome hints about where to look next (of course, in this specific case, I can hardcode the translated text, but long term, it's nice to have this right).

**Comment by kimisgold** [comment]
We've now included this pattern and its strings in the Omeka S core, so I believe this issue is resolved. If there are any errant untranslated strings I've missed, please feel free to reopen.
