### ISSUE TITLE
Test banner setting

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/centerrow#49]
There is now a theme setting that allows users to select a banner image to appear across site views. In additional settings, they can control:

* the maximum height of the banner for both mobile and desktop widths
* where to position the image within the banner container when the container ratio has a much greater width than height

Note: we're testing this setting across a bunch of themes, and I decided to omit the full width setting for Center Row, as full bleed doesn't really fit the look of this theme.

This is on the `master` branch and should be tested on desktop and mobile browsers.

**Comment by katknow** [comment]
For some reason on this one I'm not getting any options to edit the banner on the back end. I'm getting the "Your branch is up to date with 'origin/master'. nothing to commit, working tree clean" message so I think I'm in the correct place.

**Comment by kimisgold** [comment]
Can you look in the history and check if you can see this latest commit?

![image](https://user-images.githubusercontent.com/606764/141493097-c0fb380a-9b87-435e-b23b-39a0dfba8ba7.png)

**Comment by katknow** [comment]
It was showing the history, and this morning I pulled again. It said nothing to commit, but when I pulled it said there were almost 2000 changes so maybe mine was lagging for some reason? Testing now.

**Comment by katknow** [comment]
Mobile works properly with provided image.
