### ISSUE TITLE
Showcase images - sizing and spacing issues

### ISSUE THREAD

**Issue by jannellelegg** [omeka-s-themes/centerrow#5]
Showcase images (files of different size) are creating sizing and spacing issues.
![screen shot 2016-10-24 at 2 33 44 pm](https://cloud.githubusercontent.com/assets/5897725/19658747/1d939928-99f7-11e6-9e12-39d5a3e19e2f.png)
![screen shot 2016-10-24 at 2 35 39 pm](https://cloud.githubusercontent.com/assets/5897725/19658760/2925b9ec-99f7-11e6-9a23-3c6677269e69.png)

In some cases the sizing differences result in a different number of images per row, or large gaps in the rows.

Additionally, the item titles are cut-off mid-word.

**Comment by jannellelegg** [comment]
Modifying the thumbnail sizes produces uniform, images, but title spacing is still an issue:

![screen shot 2016-10-24 at 2 54 31 pm](https://cloud.githubusercontent.com/assets/5897725/19659421/d365b414-99f9-11e6-9284-e5c38bf8b10c.png)
![screen shot 2016-10-24 at 2 54 42 pm](https://cloud.githubusercontent.com/assets/5897725/19659424/d75fffca-99f9-11e6-96b6-43e0d6dc5f98.png)

**Comment by kimisgold** [comment]
Some breathing room's been added. Update and let me know if that's better.

**Comment by jannellelegg** [comment]
I think that looks better, and the title issue has also been resolved. Would it be possible to move the image caption field closer to the title?

![screen shot 2016-10-26 at 10 49 15 am](https://cloud.githubusercontent.com/assets/5897725/19731046/2244dc2e-9b6a-11e6-8248-83982c505f1c.png)
