### ISSUE TITLE
Pages with children not opening in menu

### ISSUE THREAD

**Issue by AlyxTaj** [omeka-s-themes/centerrow#50]
Hello,

We have just upgraded to the latest version of centerrow for exhibits on our Omeka S instance.
There, the menu suddenly did not respond when trying to access pages with children pages (pages without children could be accessed without a problem). Instead, all that was generated in the href was a "#" following the active page.
We have come back to the previous version and everything works fine.

My first guess is that it would have smt to do with the /common/view/accessible-mega-menu.phtml file ?

Regarding our system : 
![image](https://user-images.githubusercontent.com/33459965/146371696-04fda1fc-51bf-47fa-adfd-512aba119582.png)

Thank you in advance,

**Comment by kimisgold** [comment]
With the new menus, the parent link in the top level toggles the menu open or closed. The actual link to the parent page is repeated in the child menu and should take you to the actual page. This is a design decision made with touch devices in mind. When using touchscreens, it's not always obvious what that top level parent link should do when tapped: go to a page or open the child menu. This was a problem with the previous version of Center Row that I sought to address in this version. All links in the child menu will go to a page, where top level navigation items with children will toggle the child menu.
