### ISSUE TITLE
Test updated lightgallery, pdf display

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/centerrow#52]
Center Row has been updated with the [same lightgallery updates The Daily received](https://github.com/omeka-s-themes/thedaily/issues/43), additionally with support for PDFs. 

**Test that PDFs appear within the lightgallery, both standalone and alongside other visual media.** The other changes are pretty much identical to The Daily's update, but just in case, make sure that the following features carried over to this theme as expected:

*  Supports common visual media attachments (.jpg,.gif, .png, Youtube video, mp4)
*  Can be maximized to fullscreen.
*  Users can pan and zoom still 
* The "download" button links to the file source. It will download files where applicable, or go to the original Youtube link.

This feature is on the `master` branch and should be tested on all major browsers for both desktop and mobile devices.

**Comment by sharonmleon** [comment]
Testing on a Mac with FFX, Chrome, and Safari.

PDFs appear in the light gallery on all browsers. 

With FFX and Chrome the PDF wrapper includes the zoom and download controls. In the light gallery interface there are zoom controls, but they don't work. 

In Safari there are no PDF wrapper zoom controls or download, and in the light gallery zoom controls do not work. Download does work in the light gallery interface.

**Comment by katknow** [comment]
The Zoom controls do work for me in Firefox and Chrome. Viewer works across file types, except for some wonkiness with pdfs that I believe is item specific. For some items, [it looks like I might be getting a pdf viewer inside a pdf viewer](http://dev.omeka.org/katknow/OmekaSTesting/s/test123/item/26832)? I cleared cache, refreshed, pulled, viewed in a private window, etc.:

![image](https://user-images.githubusercontent.com/84726696/161877446-8ecf19aa-ed36-4ccd-bfef-b69f49335991.png)

When I switch back to The Daily, the problem disappears. However, on when the Daily is used it looks like it's only pulling the jpeg whereas in this one it's pulling both files.

**Comment by sharonmleon** [comment]
@katknow I had extraordinarily slow load times with the pdfs.

**Comment by kimisgold** [comment]
> For some items, [it looks like I might be getting a pdf viewer inside a pdf viewer](http://dev.omeka.org/katknow/OmekaSTesting/s/test123/item/26832)?

You're seeing the browser's pdf viewer inside the lightgallery viewer, which is expected. I'm going to get rid of the disabled zoom controls appearing for PDFs to remove some ambiguity.
