### ISSUE TITLE
Flyout navigation

### ISSUE THREAD

**Issue by cillianjoy** [omeka-s-themes/centerrow#53]
Recently upgraded to Omeka-s v3.1.2 and centre row 1.7.2. Existing navigation use links on the first and second level. On hover, the second level navigation opens but disappears when you mouse off the first level item. See https://exhibitions.library.nuigalway.ie/s/interpreting-landscape-tim-robinson-and-the-west-of-ireland.
Tested on Windows 10, latest firefox, chrome, and edge.

**Comment by sharonmleon** [comment]
Tested on a Mac with FFX, Chrome, and Safari and everything is visible. However, adding a third level of navigation introduces a rule line and seem oddly positioned -- lots of height between levels.
![Screen Shot 2022-04-05 at 3 25 25 PM](https://user-images.githubusercontent.com/741480/161834319-46946712-ceab-42c6-84d2-dc820c5c60c6.png)

**Comment by kimisgold** [comment]
That seems to be an overreaching style regarding the height of links. I've limited the style to the first level of the navigation, and that should've fixed it.

**Comment by sharonmleon** [comment]
Fixed.
