### ISSUE TITLE
Thumbnail issue and zoom request

### ISSUE THREAD

**Issue by Xxyba** [omeka-s-themes/centerrow#54]
Hello,

Since the theme update, the thumbnails are showing a weird + sign instead of the actual photograph thumbnail: https://patrimoine.ihp.fr/item/3390

Do you know how I could fix that?

Also, we use to be able to slowly zoom in or out -- with many zoom levels. With the new viewer it seems we can only zoom once (pretty close), and there is only one zoom level. Any way we could go back to the old ways and many incremental zoom levels?

Thanks a lot!

**Comment by kimisgold** [comment]
The thumbnails seem to be an asset from OpenSeadragon. Can you disable that module and see if the issue persists?

Thanks for your comment on the zoom levels. I think the updated gallery has options for incrementing, and I'll look into providing control over that in a theme setting.

**Comment by kimisgold** [comment]
No, lightgallery is the javascript viewer in Center Row. Don't worry about it though: our lead developer noticed an oversight in its config that should fix your problem. I've pushed that correction, as well as the ability to zoom in and out at multiple levels. A "reset" button should also appear when you've zoomed in at all. If you're able to pull in these changes and test for yourself, I would appreciate the feedback.

**Comment by Xxyba** [comment]
Everything works great, thumbnails and zoom levels!
Thanks a lot for the ultra fast fixes! :)
