### ISSUE TITLE
Value annotations misaligned

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-themes/centerrow#55]
Seems wonky
![Screenshot 2022-05-16 at 13-24-34 Swan II · Photographs · SML Omeka S Test](https://user-images.githubusercontent.com/741480/168649047-3e986206-7e3e-4d8b-90f2-fa5ae78371e8.png)
.

**Comment by kimisgold** [comment]
I feel like this may have been fixed and I forgot to follow up here. @sharonmleon, do you mind checking if the latest version includes improved value annotations? I at least haven't been able to recreate what I'm seeing here.

**Comment by kimisgold** [comment]
I wasn't seeing this due to the length of the annotations I was using: this mainly appeared with short annotations. @sharonmleon Can, you pull and check again?

**Comment by sharonmleon** [comment]
Fixed!
