### ISSUE TITLE
Test configurable page blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/centerrow#56]
This is the theme-specific issue for omeka/omeka-s#1859. Please test this using the latest version of Omeka S on the `develop` branch.

Center Row now supports configurable resource page blocks. On a site's theme settings panel, select Center Row's "Configure resource pages" button. Test that blocks can be reordered, removed, and readded on the show views of items, media, and item sets. Center Row only has a single "Main" block region.

**Comment by katknow** [comment]
I'm getting this error on the front end:

 Error
Object of class Omeka\View\Helper\ResourcePageBlocks could not be converted to string

Details:

Error: Object of class Omeka\View\Helper\ResourcePageBlocks could not be converted to string in /var/www/html/katknow/OmekaSTesting/themes/centerrow/view/omeka/site/item/browse.phtml:36
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include()
#1 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#2 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#3 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#4 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#10 {main}

**Comment by zerocrates** [comment]
Looks like a bug/typo in centerrow's implementation.

**Comment by kimisgold** [comment]
I had implemented the blocks here before we updated the core to include some helpers with the resource page block functionality. The theme's now updated and ready for another look.

**Comment by katknow** [comment]
The item set blocks are working as described. I'm able to move things around and add/remove blocks from the item page, but for some reason the media list (and it seems only the media list) wants to align on the right:

<img width="1256" alt="Screen Shot 2022-09-23 at 5 30 56 PM" src="https://user-images.githubusercontent.com/84726696/192059376-e67a479c-7916-4892-9a9d-cbd27ce72a06.png">

When I click through to the media page, I get this error:

 Error
Object of class Omeka\View\Helper\ResourcePageBlocks could not be converted to string

Details:

Error: Object of class Omeka\View\Helper\ResourcePageBlocks could not be converted to string in /var/www/html/katknow/OmekaSTesting/themes/centerrow/view/omeka/site/media/show.phtml:12
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include()
#1 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#2 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#3 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#4 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#5 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#7 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#9 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#10 {main}

The error and the media list right alignment persists across browsers, even when hard refreshed.

**Comment by kimisgold** [comment]
I forgot to follow up on this, but it seems like it may have been fixed among a bunch of changes that have been applied since. Could you try to reproduce this media list bug?

**Comment by katknow** [comment]
Everything seems to be working as expected now
