### ISSUE TITLE
Titles breaking awkwardly 

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-themes/centerrow#6]
The titles for items are breaking awkwardly - using media block and HTML block on the page. 

![screen shot 2016-10-24 at 2 56 39 pm](https://cloud.githubusercontent.com/assets/8807816/19659612/a157ab0c-99fa-11e6-9f36-21bd7278fcb2.png)

[In Chrome and Firefox - [this page](http://dev.omeka.org/omeka-s/s/tinbox/page/doyle) is an example]

**Comment by sheilabrennan** [comment]
Fixed!
