### ISSUE TITLE
URI Dereferencer values 

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/centerrow#60]
![centerrow](https://user-images.githubusercontent.com/28012148/222507797-f6a0da2e-767d-4759-bb8a-a716a1ef40ea.PNG)

Something that came up when looking at the URI Dereferencer module: `.resource .show dt` is having an unintended effect when loading values from the URI source. The `width:18.75%` is causing the dts to word-wrap, and they probably don't need to be quite so big and bold. 

If you uncheck the width in your browser, you also see that the `text-align:right` is  illustrating how the divs are loading as different widths, so that's a third problem. 

![centerrow2](https://user-images.githubusercontent.com/28012148/222508882-b27ab841-2d38-4106-9a7e-24a7749b49c6.PNG)

I'll leave this page as-is so you can check it out easily:
http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item/3618

**Comment by allanaaa** [comment]
The theme improvements look really good.

1) The annotation bubble on the Omeka resource value is on its own line, rather than inline. Expanded annotations look great. 

![centerrow](https://user-images.githubusercontent.com/28012148/224099312-6c597783-d0cc-4ec7-9ea1-7d4ed931491a.PNG)

2) Everything moves really nicely when you resize, but in the mobile mode there is more whitespace inside the URI Dereferencer expanded block than in the regular dt/dd display. 

```
.resource.show dt {
	margin-bottom: 6px;
}

.resource.show .property dl dt, .resource.show .property dl dd {
	margin-bottom: 12px;
}
```

So you could take the 12 down to 6 for the dts (not the dds) and it would look more consistent. 

![centerrow3](https://user-images.githubusercontent.com/28012148/224105819-5ec0e4df-e189-4c08-805d-ca5f535a0a12.PNG)

3) I don't look at mobile a lot, so I may as well mention this while I'm looking at it: feels like the "padding: 0 24px" on the dts and dds is taking up a lot of real estate at this width (the purple in the image above). Up to you.

```
.resource.show dt {
	width: 25%;
	font-weight: bold;
	color: #000;
	margin: 0;
	text-align: right;
	padding: 0 24px;
	font-size: 22.5px;
}

.resource.show dt ~ dd, .media-list dt ~ .resource-link {
	width: 75%;
	padding: 0 24px;
	margin-left: 0;
}
```

**Comment by kimisgold** [comment]
@allanaaa I think these latest fixes should cover those points. They're ready to pull and look at.

**Comment by allanaaa** [comment]
Looks great, thanks!
