### ISSUE TITLE
No forward/backward arrows visible in lightbox for resource with multiple images attached

### ISSUE THREAD

**Issue by alyssafahringer** [omeka-s-themes/centerrow#7]
See [this item](http://dev.omeka.org/omeka-s/s/tinbox/item/17600) for an example. Still able to move backward and forward between images, but no arrows appear. Happens in Chrome and Firefox.

**Comment by kimisgold** [comment]
Whoops, the UI images hadn't been included in the theme. Should be fixed in 582a0bbcab1efca9ca03a95c0cf8dcbf7695d0bc.

**Comment by sheilabrennan** [comment]
Arrows in lightbox are appearing!
