### ISSUE TITLE
Child nav and property labels overlap content on mobile

### ISSUE THREAD

**Issue by mebrett** [omeka-s-themes/centerrow#9]
On mobile or very narrow browser window (anything under about 460 wide in responsive viewers in Firefox and Chrome), the text of the left hand child page nav in a site page, and the text of property labels on item pages, bleeds over into the content area.
<img width="554" alt="screen shot 2016-10-26 at 8 45 56 am" src="https://cloud.githubusercontent.com/assets/2314070/19726537/67f28c0a-9b59-11e6-88d9-abcd838f4102.png">
<img width="457" alt="screen shot 2016-10-26 at 8 46 08 am" src="https://cloud.githubusercontent.com/assets/2314070/19726538/67f35216-9b59-11e6-8cfb-9508e116437c.png">

Tested on Chrome, Firefox, and iPhoneSafari
@kimisgold

**Comment by mebrett** [comment]
Page in question: http://dev.omeka.org/omeka-s/s/tinbox/page/canon

**Comment by kimisgold** [comment]
Yesterday I made some adjustments that should fix the property names, and I just adjusted the submenus for mobile devices.

**Comment by mebrett** [comment]
Yup, fixed. Thanks.
